### ISSUE TITLE
Would it be possible to add linux ARM build?

### ISSUE THREAD

**Issue by jmatis** [kbst/kbst#18]
I have an arm playground in aws and wanted to test kubestack from there - could you pleaseit in next release?

**Comment by pst** [comment]
The CLI would probably build just fine. But the major features depend on starting Docker containers to run Terraform in and Docker containers to act as K8s nodes. The latter relying on KinD. So that's more complicated.

What is your use case?

**Comment by clakeb** [comment]
KinD is working on M1. I can get it to work with the `kbst init {cloud provider}` generated config but not with the new online builder generated config (multi-cluster).

**Comment by pst** [comment]
@clakeb what error are you getting? I'm not quite seeing the connection between M1 and Linux ARM builds here. If it works for single cluster configurations, it's unlikely it's a processor architecture issue. Most likely you're already getting a Terraform error of some sorts, right?

If you have multi-cluster, the default ingress of the KinD clusters are conflicting on the ports. You would have to put them on different ports using `http_port` and `https_port` for each cluster's loc configuration.

But I am planning to deprecate the local environment, since its usefulness is limited because most users integrate the Kubestack clusters alongside other infrastructure provisioned via Terraform from the same root module. And it's not feasible to support these in the local environment.

I suggest you continue with step 2 of the tutorial.
